### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by yangwei132** [zh320/efficient-image-super-resolution-pytorch#1]
I wanted to use my own data, but after modification, only validation, no training. How should I solve it？
![123456](https://github.com/zh320/efficient-image-super-resolution-pytorch/assets/97602091/6bffe809-4f79-4dca-a6e1-3959f4f0e87a)

**Comment by zh320** [comment]
Would you please check this line

> https://github.com/zh320/efficient-image-super-resolution-pytorch/blob/2394bb62d2a1ac17f39dceb5bed3dfeca749c3a6/datasets/sr_base_dataset.py#L42

please check your len(hr_images) before and after this line.
Best

**Comment by zh320** [comment]
Since there is no further question, I will close this issue. You may reopen it or create a new issue if you have further question.
