### ISSUE TITLE
A new question

### ISSUE THREAD

**Issue by yangwei132** [zh320/efficient-image-super-resolution-pytorch#2]
When I test the code, I have another problem.  Please tell me how to solve it!
![123](https://github.com/zh320/efficient-image-super-resolution-pytorch/assets/97602091/8915aad5-61b1-4238-aaa4-47098878ea01)

**Comment by zh320** [comment]
Currently these codes only support batch size 1 testing (to be compatible with different input images). Please check your test_bs.

**Comment by zh320** [comment]
Since there is no further question, I will close this issue. You may reopen it or create a new issue if you have further question.
